name: payu-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - python==3.10
  - f90nml
  - nco
  - pytest
  - xarray
  - mule
  - um2nc<2
  - accessnri::yamanifest
  - netcdf4=*=nompi_*
  - experiment-generator
  - experiment-runner
  - mnctools
  - addmeta
  - pip:
    - git+https://github.com/payu-org/payu.git@master