name: rmom6-dev
channels:
  - accessnri
  - conda-forge
dependencies:
  - copernicusmarine
  - esmpy
  - jupyter
  - matplotlib
  - pip:
    - git+https://github.com/COSIMA/regional-mom6.git@rom3_setup