name: rmom6-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - esmpy
  - jupyter
  - matplotlib
  - pip:
    - git+https://github.com/COSIMA/regional-mom6.git@5b070219eeaf28495de441e2bcbf1c5cc9cee87c
