name: rmom6-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - esmpy
  - pip:
    # Current dev branch of rmom6
    - git+https://github.com/COSIMA/regional-mom6.git@49007b1a6d7ef26d4d3533d5244d64c9ee0ff8fa
    # Fork of mom6_forge
    - git+https://github.com/COSIMA/mom6_forge.git@c3088430f375df527c3d69c97570024631db5891
  # The following are not dependencies of regional-mom6 but required for the rOM3 workflow and demos. 
  - jupyter
  - matplotlib>=3.11
  - cartopy
  - cf_xarray
