name: rmom6
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - esmpy
  - pip:
    # Main branch of regional-mom6, currently set to the first tag made ready for containerised env (1.0.2)
    - git+https://github.com/COSIMA/regional-mom6.git@v1.0.2
    # Fork of mom6_forge
    - git+https://github.com/COSIMA/mom6_forge.git@1.0
  # The following are not dependencies of regional-mom6 but required for the rOM3 workflow and demos. 
  - jupyter
  - matplotlib>=3.11
  - cartopy
  - cf_xarray
