name: model-processing-dev
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - python
  - mo_pack
  - mule
  - xarray
  - pip:
    - git+https://github.com/access-nri/um2nc-standalone.git@main
    - git+https://github.com/access-nri/umfile_utils.git@main
    - git+https://github.com/ACCESS-NRI/splitnc.git@main
    - git+https://github.com/ACCESS-NRI/addmeta.git@main