name: model-processing
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - python
  - ants
  - esmf
  - mule
  - scitools-iris>=3.11.1
  - um2nc==2.1.0
  - umfile_utils==1.1.0
  - xarray