name: coastal-commons-forecast
channels:
  - accessnri
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - argopy=1.4.0
  - cartopy
  - cfgrib
  - cmocean
  - copernicusmarine=2.4.1
  - dask
  - dask[array]
  - ecmwf-opendata
  - erddapy=2.2.1
  - gsw
  - hydra-core
  - h5netcdf
  - ipdb
  - ipython
  - jinja2
  - matplotlib
  - natsort
  - netCDF4=1.7.4
  - numpy=2.5.3
  - pandas
  - pyyaml
  - s3fs
  - scipy
  - setuptools
  - xarray
  - xroms
  - zarr