name: Set up HPC target
description: |
  Set up the HPC target for deployment. This includes:
  - Check GitHub Environment configuration for the HPC target
  - Set up SSH access to the HPC target
  - Create a temporary repository directory on the HPC target
  - Set the env variable related to the hpc_target_deployment_info.json file path
  - Create a configuration env script on the HPC target that can be sourced in subsequent step
    to have the CI environment ready within the HPC system.
  - Sync repository to the HPC target

  This action exports the following environment variables used in subsequent steps:
    - TEMP_EXCHANGE_DIR_ON_HPC: path to the temporary exchange directory on the HPC target
    - TEMP_EXCHANGE_DIR_ON_GH: path to the temporary exchange directory on the GitHub runner
    - DEPLOYMENT_INFO_JSON_ON_HPC: path to the deployment info JSON file on the HPC target
    - DEPLOYMENT_INFO_JSON_ON_GH: path to the deployment info JSON file on the GitHub runner
    - REPO_PATH: path to this repository clone on the HPC target
    - GH_ENV_EXPORT_SCRIPT: path on the HPC target of the bash script sourced to export variables
      from the GitHub runner environment

inputs:
  target-name:
    description: "The GitHub Environment corresponding to the HPC target to set up"
    required: true
  user:
    description: "Username for SSH access to the HPC target."
    required: true
  host:
    description: "Hostname for SSH access to the HPC target."
    required: true
  ssh-key:
    description: "Private SSH key for access to the HPC target."
    required: true
  ssh-key-passphrase:
    description: "Passphrase for the private SSH key."
    required: false
  token:
    description: "GitHub token with read permissions to this repository."
    required: false
    default: true
outputs:
  private-key-path:
    description: "Path to the private SSH key file created in this action for SSH access to the HPC target. This can be used in subsequent steps that require SSH access to the HPC target."
    value: ${{ steps.ssh.outputs.private-key-path }}
runs:
  using: composite
  steps:
    # Sanity check that all needed GitHub Environment variables and secrets are non-empty
    - name: Check GitHub Environment configuration
      shell: bash
      run: |
        if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
          set -x
        fi
        vars_unset=false
        vars=(
          GROUP_OWNER
          PBS_PROJECT
          PBS_STORAGE
          SINGULARITY_EXE
          JQ_EXE
          STABLE_PRODUCTION_BASE_DIR
        )
        for var in "${vars[@]}"; do
          if [[ -z "${!var:-}" ]]; then
            msg="Variable '${var}' is unset or empty in the '${{ inputs.target-name }}' GitHub Environment. "
            msg+="Set this variable before re-running this workflow. "
            msg+="For further information, see the README section 'GitHub Environments Setup'."
            echo "::error::$msg"
            vars_unset=true
          fi
        done
        [[ $vars_unset == true ]] && exit 1 || true

    - name: Set up SSH
      uses: access-nri/actions/.github/actions/setup-ssh@main
      id: ssh
      with:
        hosts: ${{ inputs.host }}:hpc
        user: ${{ inputs.user }}
        private-key: ${{ inputs.ssh-key }}
        private-key-passphrase: ${{ inputs.ssh-key-passphrase }}

    # We create a temporary directory on the HPC system, to exchange files between
    # the GitHub runner and the HPC system.
    # We also define the path to the correspective directory and other useful files
    # on the GitHub runner so we can use them in subsequent steps both within the HPC
    # system and the GitHub runner.
    - name: Create temporary exchange directory on HPC system
      id: create-exchange-dir
      shell: bash
      run: |
        if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
          set -x
        fi
        temp_exchange_dir=$(
          ssh hpc 'mktemp -d'
        )
        echo "TEMP_EXCHANGE_DIR_ON_HPC=$temp_exchange_dir" >> $GITHUB_ENV
        # Set the path to the temporary exchange directory on the GitHub runner
        temp_exchange_dir_on_gh_runner="${{github.workspace}}/from_hpc"
        echo "TEMP_EXCHANGE_DIR_ON_GH=$temp_exchange_dir_on_gh_runner" >> $GITHUB_ENV
        # Set the name of the deployment info JSON file
        deployment_info_json_filename=deployment_info_${{ job.check_run_id }}.json
        # Set the path to the deployment_info.json file on the HPC
        echo "DEPLOYMENT_INFO_JSON_ON_HPC=$temp_exchange_dir/$deployment_info_json_filename" >> $GITHUB_ENV
        # Set the path to the deployment_info.json file on the GH runner
        echo "DEPLOYMENT_INFO_JSON_ON_GH=$temp_exchange_dir_on_gh_runner/$deployment_info_json_filename" >> $GITHUB_ENV
        # Path to the repository clone on the HPC system
        echo "REPO_PATH=$temp_exchange_dir/repository_clone" >> $GITHUB_ENV

    # We create a bash script to export variables from
    # the GitHub runner environment to the HPC system
    - name: Set GitHub runner environment export script
      shell: bash
      run: |
        if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
          set -x
        fi
        # Set GitHub runner environment export script path within the HPC system
        gh_env_export_script_on_hpc="$TEMP_EXCHANGE_DIR_ON_HPC/gh_env_exports_on_hpc.sh"
        gh_env_export_script_on_gh_runner=gh_env_exports_on_gh_runner.sh
        # Generate GitHub runner environment export script
        source infrastructure/scripts/github_runner_env_export.sh > "$gh_env_export_script_on_gh_runner"
        echo "GH_ENV_EXPORT_SCRIPT=$gh_env_export_script_on_hpc" >> $GITHUB_ENV
        # Copy the GitHub runner environment export script to the HPC system
        rsync "$gh_env_export_script_on_gh_runner" hpc:"$gh_env_export_script_on_hpc"

    # We clone this repository to make the repository files available within the HPC system.
    # For simplicity, instead of actually cloning the whole repository, we just initialise
    # an empty git repository, add the remote, fetch the specific commit and check it out.
    # This saves time and disk space, especially for large repositories.
    - name: Clone repository on HPC system
      id: clone-repo
      shell: bash
      env:
        GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      run: |
        ssh hpc << 'HPC_SSH_EOF'
          if [[ '${{ env.CONTAINERISED_ENVS_DEBUG }}' == 1 ]]; then
            set -x
          fi
          set -euo pipefail
          repo_path='${{ env.REPO_PATH }}'
          git config --list
          # Initialise an empty git repository 
          git init "$repo_path"
          # Add remote with GH_TOKEN for authentication
          git -C "$repo_path" \
            remote add origin 'https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git'
          # Fetch the specific commit and check it out
          git -C "$repo_path" \
            fetch --depth 1 origin '${{ env.GITHUB_SHA }}'
          git -C "$repo_path" \
            checkout FETCH_HEAD
        HPC_SSH_EOF