name: Deploy containerised environment
description: |
  Deploy a containerised environment to the HPC system.
on:
  workflow_call:
    inputs:
      environment:
        description: |
          Name of the environment to deploy. 
          Must match a subfolder name under this repository's `environments/` directory.
        required: true
        type: string
      version:
        description: |
          Version to deploy (e.g., 1.0.0).
          Required if any of staging, test, or production is true.
        required: false
        default: dummy_version
        type: string
      staging:
        description: |
          Deploy the environment to the STAGING directory.
          Default is true.
        type: boolean
        required: false
        default: true
      production:
        description: |
          Deploy the environment module to the PRODUCTION directory.
          Default is false.
        type: boolean
        required: false
        default: false
      is_stable:
        description: |
            true for STABLE environments, false for DEVELOPMENT environments.
            Default is false.
        type: boolean
        default: false
        required: false

jobs:
  sanity_checks:
    name: Sanity checks
    runs-on: ubuntu-latest
    steps:
      # Check that if staging or production is true, then version must be provided
      - name: Check version input
        run: |
          if [[ '${{ inputs.staging }}' == true || \
             '${{ inputs.production }}' == true ]] && \
             [[ '${{ inputs.version }}' == dummy_version ]]; then
            echo "::error::'version' input must be provided when at least one of 'staging', 'test', or 'production' is true."
            exit 1
          fi
      # Check that if production is true, then staging must be true
      - name: Check staging input
        run: |
          if [[ '${{ inputs.production }}' == true && '${{ inputs.staging }}' == false ]]; then
            echo "::error::'staging' input must be true when 'production' is true."
            exit 1
          fi
  
  approval-for-production-deployment:
    name: Approval for production deployment
    runs-on: ubuntu-latest
    environment: production
    needs: sanity_checks
    if: inputs.production == true
    steps:
      - name: Approval granted
        run: echo "Production deployment approved."

  get-date:
    name: Get current date
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get date
        id: get-date
        run: |
          date=$(TZ='Australia/Sydney' date '+%FT%T %Z')
          echo "date=$date" >> "$GITHUB_OUTPUT"

  # We take the HPC targets for the deployment from the hpc_targets file 
  # and place them in a JSON array to be used in the deployment job
  # with a matrix strategy
  get-hpc-targets:
    runs-on: ubuntu-latest
    outputs:
      hpc-targets: ${{ steps.get-targets.outputs.hpc-targets }}
    env:
      HPC_TARGETS_FILENAME: hpc_targets
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Get HPC targets
        id: get-targets
        run: |
          # First check for a file in the overrides folder
          hpc_targets_file="environments/${{ inputs.environment }}/overrides/$HPC_TARGETS_FILENAME"
          if [[ ! -f "$hpc_targets_file" ]]; then
            hpc_targets_file="defaults/$HPC_TARGETS_FILENAME"
            if [[ ! -f "$hpc_targets_file" ]]; then
              echo "No HPC targets file found at '$hpc_targets_file'. Please provide one to specify the HPC targets for the deployment."
              exit 1
            fi
          fi
          # Get unique HPC targets from the file and set as output in JSON array format
          targets=$(
            jq -Rcs 'split("\n") | map(select(length > 0)) | map(ascii_downcase) | unique' "$hpc_targets_file"
          )
          echo "hpc-targets=$targets" >> $GITHUB_OUTPUT
          echo "hpc-targets-file=$hpc_targets_file" >> $GITHUB_OUTPUT

      # Make sure that all HPC targets specified exist as GitHub Environments in the repository
      - name: Sanity check on HPC targets
        run: |
          endpoint='repos/{owner}/{repo}/environments'
          for target in $(echo "${{ steps.get-targets.outputs.hpc-targets }}" | jq -r '.[]'); do
            if ! gh api "$endpoint/$target" &> /dev/null; then
              msg="HPC target '$target' does not exist as a GitHub Environment in this repository. "
              msg+="Please create a GitHub Environment with this name or remove it from the '${{ steps.get-targets.outputs.hpc-targets-file }}' file."
              echo "::error::$msg"
              exit 1
            fi
          done

  deploy:
    needs: [sanity_checks, approval-for-production-deployment, get-date, get-hpc-targets]
    runs-on: ubuntu-latest
    #  Also run if approval-for-production-deployment is skipped (i.e., when inputs.production is false)
    if: always() && !cancelled() && needs.approval-for-production-deployment.result != 'failure'
    concurrency:
      group: "${{ matrix.hpc-target }}-${{ inputs.environment }}-${{ inputs.version }}"
      cancel-in-progress: true
    strategy:
      matrix:
        hpc-target: ${{ fromJson(needs.get-hpc-targets.outputs.hpc-targets) }}
      fail-fast: false
    environment: ${{ matrix.hpc-target }}
    env:
      GROUP_OWNER: '${{ vars.GROUP_OWNER }}'
      PBS_PROJECT: '${{ vars.PBS_PROJECT }}'
      PBS_STORAGE: '${{ vars.PBS_STORAGE }}'
      SINGULARITY_EXE: '${{ vars.SINGULARITY_EXE }}'
      JQ_EXE: '${{ vars.JQ_EXE }}'
      STABLE_PRODUCTION_BASE_DIR: '${{ vars.STABLE_PRODUCTION_BASE_DIR }}'
      MODULE_NAME: '${{ inputs.environment }}'
      MODULE_VERSION: '${{ inputs.version }}'
      MODULE_TYPE: ${{ inputs.is_stable == true && 'STABLE' || 'DEVELOPMENT' }}
      HPC_TARGET: ${{ matrix.hpc-target }}
      HPC_NAME: ${{ vars.HPC_NAME }}
      STARTED_AT: ${{ needs.get-date.outputs.date }}
      PAYU_TELEMETRY_CONFIG_PATH: '${{ secrets.PAYU_TELEMETRY_CONFIG_PATH }}'
      DEPLOYMENT_WORKFLOW_RUN_ID: ${{ github.run_id }}
      DEPLOYMENT_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Set debug mode
        run: |
          # echo "CONTAINERISED_ENVS_DEBUG=${{ runner.debug }}" >> $GITHUB_ENV
          echo "CONTAINERISED_ENVS_DEBUG=1" >> $GITHUB_ENV
      
      # This action exports the following environment variables used in subsequent steps:
      # - TEMP_EXCHANGE_DIR_ON_HPC: path to the temporary exchange directory on the HPC target
      # - TEMP_EXCHANGE_DIR_ON_GH: path to the temporary exchange directory on the GitHub runner
      # - DEPLOYMENT_INFO_JSON_ON_HPC: path to the deployment info JSON file on the HPC target
      # - DEPLOYMENT_INFO_JSON_ON_GH: path to the deployment info JSON file on the GitHub runner
      # - REPO_PATH: path to this repository clone on the HPC target
      # - GH_ENV_EXPORT_SCRIPT: path on the HPC target of the bash script sourced to export variables
      #   from the GitHub runner environment
      - name: Set up HPC target
        uses: ./.github/actions/set_up_hpc_target
        id: set-up-hpc-target
        with:
          target-name: ${{ matrix.hpc-target }}
          user: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-key-passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          token: ${{ secrets.REPO_CONTENT_READ_TOKEN }}

      - name: Deploy staging environment
        if: inputs.staging
        id: deploy-staging
        run: |
          ssh hpc <<'HPC_SSH_EOF'
            set -euo pipefail
            if [[ '${{ env.CONTAINERISED_ENVS_DEBUG }}' == 1 ]]; then
              set -x
            fi
            # GitHub runner environment export
            source '${{ env.GH_ENV_EXPORT_SCRIPT }}'
            # Set job name prefix
            export JOB_NAME_PREFIX=staging
            # Set DEPLOYMENT_STAGE
            export DEPLOYMENT_STAGE=STAGING
            source "$INFRA_SCRIPTS_DIR/submit_pbs_job.sh" "$INFRA_SCRIPTS_DIR/build_and_deploy.sh"
          HPC_SSH_EOF
      
      - name: Deploy production environment
        if: inputs.production
        id: deploy-production
        run: |
          ssh hpc <<'HPC_SSH_EOF'
            set -euo pipefail
            if [[ '${{ env.CONTAINERISED_ENVS_DEBUG }}' == 1 ]]; then
              set -x
            fi
            # GitHub runner environment export
            source '${{ env.GH_ENV_EXPORT_SCRIPT }}'
            # Set job name prefix
            export JOB_NAME_PREFIX=production
            # Set DEPLOYMENT_STAGE
            export DEPLOYMENT_STAGE=PRODUCTION
            source "$INFRA_SCRIPTS_DIR/submit_pbs_job.sh" "$INFRA_SCRIPTS_DIR/build_and_deploy.sh"
          HPC_SSH_EOF
    
      # Get files within the TEMP_EXCHANGE_DIR_ON_HPC to GitHub Runner
      - name: Get files from temporary exchange directory on HPC system
        if: always() && !cancelled() && steps.set-up-hpc-target.outcome == 'success'
        id: get-files-from-hpc
        run: |
          set -euo pipefail
          if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
            set -x
          fi
          # Get files from TEMP_EXCHANGE_DIR_ON_HPC to GitHub runner
          mkdir -p "$TEMP_EXCHANGE_DIR_ON_GH"
          rsync \
            -avh \
            --no-perms \
            --no-owner \
            --no-group \
            hpc:"$TEMP_EXCHANGE_DIR_ON_HPC/" "$TEMP_EXCHANGE_DIR_ON_GH"
          
      - name: Sanity check on deployment info JSON file
        if: always() && !cancelled() && steps.get-files-from-hpc.outcome == 'success'
        continue-on-error: true
        id: deployment-info-json-sanity-check
        run: |
          set -euo pipefail
          if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
            set -x
          fi
          if [[ ! -f "$DEPLOYMENT_INFO_JSON_ON_GH" ]]; then
            echo "::error:: The deployment info JSON file was not produced."
            exit 1
          else
            cat "$DEPLOYMENT_INFO_JSON_ON_GH"
          fi
    
      - name: Set message for summary
        # We always run this if the deployment-info-json-sanity-check step succeeds.
        if: always() && !cancelled() && steps.deployment-info-json-sanity-check.outcome == 'success'
        id: set-message-summary
        uses: ./.github/actions/set_message
        with:
          message-type: summary
          data-file: ${{ env.DEPLOYMENT_INFO_JSON_ON_GH }}

      - name: Set message in the step summary
        # We always run this if the set-message-summary step succeeds.
        if: always() && !cancelled() && steps.set-message-summary.outcome == 'success'
        run: cat "${{ steps.set-message-summary.outputs.message-file-path }}" >> $GITHUB_STEP_SUMMARY

      - name: Save deployment info JSON as an artifact
        # We always run this if the deployment-info-json-sanity-check step succeeds.
        if: always() && !cancelled() && steps.deployment-info-json-sanity-check.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.DEPLOYMENT_INFO_JSON_ON_GH }}
          name: deployment_info_${{ matrix.hpc-target }}_${{ inputs.environment }}_${{ inputs.version }}
    
      - name: Delete staging files
        # Delete staging files if we deploy to production, or if there are no deployments 
        # (e.g., closed PR)
        if: inputs.production == true || inputs.staging == false
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.set-up-hpc-target.outputs.private-key-path }} /bin/bash <<EOT
            set -euo pipefail
            if [[ ${CONTAINERISED_ENVS_DEBUG:-0} == 1 ]]; then
              set -x
            fi
            # Set configuration environment
            source '$REPO_PATH/$ENV_CONFIG_FILENAME'
            export DEPLOYMENT_STAGE=STAGING
            # Delete staging files
            "\$INFRA_SCRIPTS_DIR/delete_staging_files.sh" ${{ github.event.number }}
          EOT
    
      # Delete the temporary exchange directory that we created on the HPC system
      - name: Delete temporary exchange directory on HPC system
        id: delete-temp-dir
        if: always() && steps.set-up-hpc-target.outcome == 'success'
        run: ssh hpc 'rm -rfv ${{ env.TEMP_EXCHANGE_DIR_ON_HPC }}'
