name: Deploy payu telemetry config to PRODUCTION
description: |
  This workflow deploys payu telemetry config to PRODUCTION.
  The telemetry config's specification is taken from payu's repository and is deployed to the
  HPC targets specified in the hpc-targets input.

on:
  workflow_dispatch:
    inputs:
      hpc-targets:
        description: |
          Comma-separated list of HPC targets where to deploy payu's telemetry configuration (e.g., gadi,setonix).
          Each target must match the name of a GitHub Environment defined within this repo.
        required: true
        type: string

env:
  TELEMETRY_CONFIG_NAME: telemetry_config.json

jobs:
  check-hpc-targets:
    name: Check HPC targets
    runs-on: ubuntu-latest
    outputs:
      hpc-targets: ${{ steps.set-hpc-targets.outputs.hpc-targets }}
    env:
      HPC_TARGETS: ${{ inputs.hpc-targets }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Make sure that all HPC targets specified exist as GitHub Environments in the repository
      - name: Sanity check on HPC targets
        run: |
          endpoint='repos/${{ github.repository }}/environments'
          IFS=',' read -ra hpc_targets <<< "$HPC_TARGETS"
          for target in "${hpc_targets[@]}"; do
            if ! gh api "$endpoint/$target" > /dev/null; then
              msg="HPC target '$target' does not exist as a GitHub Environment in this repository. "
              msg+="Please create a GitHub Environment with this name or remove it from this workflow's inputs."
              echo "::error::$msg"
              exit 1
            fi
          done
      
      - name: Convert input HPC targets to JSON array
        id: set-hpc-targets
        run: |
          hpc_targets=$(
            echo "$HPC_TARGETS" | \
            jq -Rc 'split(",")'
          )
          echo "$hpc_targets"
          echo "hpc-targets=$hpc_targets" >> $GITHUB_OUTPUT
  
  # Get the telemetry config template and schema from payu's repository
  get-telemetry-config:
    needs: check-hpc-targets
    runs-on: ubuntu-latest
    env:
      TELEMETRY_CONFIG_URL: https://raw.githubusercontent.com/payu-org/payu/refs/heads/davide/725-payu-telemetry-updates/payu/telemetry/telemetry_config.json
      TELEMETRY_SCHEMA_URL: https://raw.githubusercontent.com/payu-org/payu/refs/heads/davide/725-payu-telemetry-updates/payu/telemetry/telemetry_config.schema.json
    steps:
      - name: Get payu telemetry config from payu's repository
        run: curl -sL $TELEMETRY_CONFIG_URL -o telemetry_config_template.json
      
      - name: Get payu telemetry schema from payu's repository
        run: curl -sL $TELEMETRY_SCHEMA_URL -o telemetry_config_schema.json
      
      - name: Upload telemetry config and schema as artifact
        uses: actions/upload-artifact@v7
        with:
          name: telemetry_config
          path: |
            telemetry_config_template.json
            telemetry_config_schema.json

#   approval-for-production-deployment:
#     name: Approval for production deployment
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Approval granted
#         run: echo "Production deployment approved."

  deploy:
    needs: [check-hpc-targets, get-telemetry-config]
    runs-on: ubuntu-latest
    concurrency:
      group: "payu-telemetry-config-deployment-${{ matrix.hpc-target }}"
      cancel-in-progress: true
    strategy:
      matrix:
        hpc-target: ${{ fromJson(needs.check-hpc-targets.outputs.hpc-targets) }}
      fail-fast: false
    environment: ${{ matrix.hpc-target }}
    env:
      PAYU_TELEMETRY_URL: ${{ secrets.PAYU_TELEMETRY_URL }}
      PAYU_TELEMETRY_PROXY_URL: ${{ secrets.PAYU_TELEMETRY_PROXY_URL }}
      PAYU_TELEMETRY_TOKEN: ${{ secrets.PAYU_TELEMETRY_TOKEN }}
      PAYU_TELEMETRY_HOSTNAME: ${{ secrets.HPC_NAME }}
      PAYU_TELEMETRY_CONFIG_PATH: ${{ secrets.PAYU_TELEMETRY_CONFIG_PATH }}
      HOST: ${{ secrets.HOST }}
      HOST_DATA: ${{ secrets.HOST_DATA }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
      USER: ${{ secrets.USER }}
      OWNER: ${{ vars.OWNER }}
      GROUP_OWNER: ${{ vars.GROUP_OWNER }}
    steps:
      # Sanity check that all needed GitHub Environment secrets are non-empty
    - name: Check GitHub Environment configuration
      run: |
        unset=false
        # Create function to check the existence of a required variable or secret in the
        # GitHub Environment, and to print an error message if it does not exist or is empty
        check() {
          local type=$1 env_var=$2 name=${3:-$2}
          if [[ -z "${!env_var:-}" ]]; then
            msg="The ${type} '${name}' is unset or empty in the '${{ matrix.hpc-target }}' GitHub Environment. "
            msg+="Set this ${type} before re-running this workflow. "
            msg+="For further information, see the 'GitHub Environments Setup' README section."
            echo "::error::$msg"
            unset=true
          fi
        }
        ## Secrets
        check secret PAYU_TELEMETRY_URL
        check secret PAYU_TELEMETRY_PROXY_URL
        check secret PAYU_TELEMETRY_TOKEN
        check secret PAYU_TELEMETRY_HOSTNAME HPC_NAME
        check secret PAYU_TELEMETRY_CONFIG_PATH
        check secret HOST
        check secret SSH_KEY
        check secret USER
        ## Variables
        check variable OWNER
        check variable GROUP_OWNER
        [[ $unset == true ]] && exit 1 || true
    
    - name: Download telemetry config artifact
      uses: actions/download-artifact@v8
      id: download-telemetry-config
      with:
        name: telemetry_config
    
    - name: Interpolate telemetry config template using Jinja2
      uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
      with:
        template: "${{ steps.download-telemetry-config.outputs.download-path }}/telemetry_config_template.json"
        output_file: ${{ env.TELEMETRY_CONFIG_NAME }}
        strict: true
    
    - name: Validate telemetry config against schema
      run: |
        schema="${{ steps.download-telemetry-config.outputs.download-path }}/telemetry_config_schema.json"
        npx ajv-cli@5.0.0 validate \
          --spec=draft7 \
          -s "$schema" \
          -d "$TELEMETRY_CONFIG_NAME"

    - name: Set up SSH
      uses: access-nri/actions/.github/actions/setup-ssh@main
      id: set-up-ssh
      with:
        hosts: |
          ${{ env.HOST }}
          ${{ env.HOST_DATA }}
        private-key: ${{ env.SSH_KEY }}
        private-key-passphrase: ${{ env.SSH_KEY_PASSPHRASE }}
    
    - name: Create payu telemetry config parent directory
      run: |
        ssh $USER@$HOST \
          -i ${{ steps.set-up-ssh.outputs.private-key-path }} \
          mkdir -p $(dirname $PAYU_TELEMETRY_CONFIG_PATH)
    
    - name: Deploy telemetry config
      run: |
        rsync -e 'ssh -i ${{ steps.set-up-ssh.outputs.private-key-path }}' \
          -avz \
          $TELEMETRY_CONFIG_NAME \
          "$USER@${{ env.HOST_DATA || env.HOST }}:$PAYU_TELEMETRY_CONFIG_PATH"

    - name: Set permissions
      run: |
        ssh $USER@$HOST \
          -i ${{ steps.set-up-ssh.outputs.private-key-path }} << EOF
        set -euo pipefail
        set -x
        # Reset existing acls
        setfacl -b '$PAYU_TELEMETRY_CONFIG_PATH'
        # Change group ownership
        chgrp $GROUP_OWNER '$PAYU_TELEMETRY_CONFIG_PATH'
        # Set read and write permissions to owner, read permissions to group, and no permissions to others
        chmod u=rw-,g=r--,o= '$PAYU_TELEMETRY_CONFIG_PATH'
        # Set specific acls for OWNER (read and write)
        setfacl -m u:$OWNER:rw- '$PAYU_TELEMETRY_CONFIG_PATH'
        EOF